version: '3.3'
services:
  db:
    image: postgres:11-alpine
    container_name: geofishing_db
    ports:
      - "5436:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fishing
      - POSTGRES_PASSWORD=fishing
      - POSTGRES_DB=fishing

  geofishing:
    build: .
    image: revalle88/geofishing_app
    container_name: geofishing_app
    environment:
      - DJANGO_DEBUG=True
    volumes:
      - ./fishing:/app/fishing
      - ./app:/app/app
      - ./blog:/app/blog
      - ./media:/app/media
      - ./static:/app/static
    ports:
      - 6556:6556
    command: python manage.py runserver 0.0.0.0:6556
    entrypoint:
      - /app/entry_point.sh
    depends_on:
      - db
    restart: always
    stdin_open: true
    tty: true

  mongodb:
      image: mongo:latest
      container_name: geofishing_mongodb
      hostname: mongodb
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/mongo:/data/db
      ports:
          - 27027:27017
      command: mongod --logpath=/dev/null # --quiet