version: '3.7'
services:
  db:
    image: postgres
    env_file: .env
  geofishing:
    build: .
    image: fishing_geofishing
    container_name: geofishing
    volumes:
      - ./fishing:/app/fishing
      - ./app:/app/app
    ports:
      - "6556:6556"
    command: gunicorn fishing.wsgi:application --bind 0.0.0.0:6556 --workers 3
    entrypoint:
      - /app/entry_point.sh
    depends_on:
      - db
    restart: always
    stdin_open: true
    tty: true