# Generated by Django 2.1.12 on 2019-09-10 09:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(default='fishes/no-img.jpg', upload_to='fishes')),
                ('catch_ease', models.CharField(choices=[('E', 'легко'), ('M', 'средне'), ('H', 'сложно')], default='M', max_length=1)),
            ],
            options={
                'verbose_name': 'Рыба',
                'verbose_name_plural': 'Рыбы',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Метод ловли',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='pound_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lang', models.FloatField(default=50)),
                ('lat', models.FloatField(default=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('contacts', models.CharField(blank=True, max_length=200)),
                ('conditions', models.CharField(blank=True, max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fishes', models.ManyToManyField(to='app.Fish')),
            ],
            options={
                'verbose_name': 'Пруд',
                'verbose_name_plural': 'Пруды',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fishing_date', models.DateField(default=datetime.date(2019, 9, 10))),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('likes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('lang', models.FloatField(default=50)),
                ('lat', models.FloatField(default=50)),
                ('picture', models.ImageField(default='reviews/no-img.jpg', upload_to='reviews')),
                ('length', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fish_caught', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Fish')),
                ('method', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Method')),
                ('pound', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pound')),
            ],
            options={
                'verbose_name': 'Обзор',
                'verbose_name_plural': 'Обзоры',
            },
        ),
    ]
