# Generated by Django 2.1.12 on 2019-09-10 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='pound',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Pound'),
        ),
        migrations.AlterField(
            model_name='review',
            name='fishing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
