# Generated by Django 2.1.11 on 2019-08-30 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190830_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
