# Generated by Django 2.1.12 on 2019-09-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190910_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='slug',
            field=models.SlugField(null=True, verbose_name='URL'),
        ),
    ]
