# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='fishing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
