# Generated by Django 2.1.12 on 2019-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fish_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pound',
            name='slug',
            field=models.SlugField(blank=True, default='slug', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='slug',
            field=models.SlugField(blank=True, default='slug', verbose_name='URL'),
        ),
    ]
