# Generated by Django 2.1.12 on 2019-09-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190918_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pound',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL'),
        ),
    ]
