# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190124_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='lang',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='review',
            name='lat',
            field=models.FloatField(default=50),
        ),
    ]
