# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190131_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pound'),
        ),
    ]
