# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190207_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='picture',
            field=models.ImageField(default='fishes/no-img.jpg', upload_to='fishes'),
        ),
    ]
