# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190208_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='pound',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pound',
            name='lang',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='pound',
            name='lat',
            field=models.FloatField(default=50),
        ),
    ]
