# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190218_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='pound',
            name='conditions',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='pound',
            name='contacts',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
