# Generated by Django 2.1.7 on 2019-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190306_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
