# Generated by Django 2.1.7 on 2019-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='short_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
