# Generated by Django 2.1.7 on 2019-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_fish_short_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'verbose_name': 'Рыба', 'verbose_name_plural': 'Рыбы'},
        ),
        migrations.AlterModelOptions(
            name='pound',
            options={'verbose_name': 'Пруд', 'verbose_name_plural': 'Пруды'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Обзор', 'verbose_name_plural': 'Обзоры'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
