# Generated by Django 2.1.11 on 2019-08-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190604_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Review'),
        ),
    ]
