# Generated by Django 2.1.11 on 2019-08-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagetag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='A slug to identify posts by this category', max_length=255, verbose_name='slug'),
        ),
    ]
